Enhancement/standardized naming
mermaid-js/mermaid pull request #1879
Opened 2021-02-02 07:42 UTC by harshilparmar

## :bookmark_tabs: Summary
The codebase was using `logger` and `log` functionality interchangeably. So as discussed in #1449 I have changed that to `logger`. 
Resolves #1449

### :clipboard: Tasks
Make sure you
- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md) 
- [x] :bookmark: targeted `develop` branch

2021-02-02 12:08 UTC, harshilparmar commented on src/dagre-wrapper/clusters.js
> +import { logger } from '../logger'; // eslint-disable-line
It's already there in the main repo. I haven't added that.

2021-02-02 13:04 UTC, sidharthv96 commented on src/dagre-wrapper/clusters.js
> +import { logger } from '../logger'; // eslint-disable-line
Yeah, but can you try if does removing that cause any issues with eslint? If not, you can remove it.

2021-02-04 18:01 UTC, knsv requested changes
Make a bigger change and rename all log instances from logger to log as per our discussion.

2021-02-06 11:03 UTC, harshilparmar commented
@knsv Suggestion: What about changing logger.js to log.js !!

2021-02-07 09:07 UTC, knsv approved these changes
Perfect, thanks!

2021-02-07 09:07 UTC, merged