Add vitepress pluin
mermaid-js/mermaid pull request #3476
Opened 2022-09-17 02:27 UTC by emersonbottero

## :bookmark_tabs: Summary

Updating docs with plugin
Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added unit/e2e tests (if appropriate)
- [x] :bookmark: targeted `develop` branch

2022-09-17 03:53 UTC, sidharthv96 requested changes

2022-09-17 03:53 UTC, sidharthv96 commented on docs/integrations.md
> +  - [Plugin for Mermaid.js](http://localhost:3000/vitepress-plugin-mermaid/)
Hi @emersonbottero, thanks for the contribution!

Please make changes in `src/docs` as suggested in https://github.com/mermaid-js/mermaid/issues/3465#issuecomment-1249244015.

`docs` is an autogenerated folder.

Also, the URL is pointing to localhost:3000.

2022-09-17 15:41 UTC, emersonbottero commented on docs/integrations.md
> +  - [Plugin for Mermaid.js](http://localhost:3000/vitepress-plugin-mermaid/)
I changed the correct file.

1 - Shouldn't we add the root docs to the gitignore file?
2 - If you like I can port the current documentation to use vitepress, (there should be no changes to the md files itself.)
and it would still use github actions to generate and deploy.
you can see examples bellow:
[Vitepress](https://vitepress.vuejs.org/)
[Vitest](https://vitest.dev/)
[Vite](https://vitejs.dev/)

We can style as you want.

2022-09-18 16:26 UTC, sidharthv96 commented on docs/integrations.md
> +  - [Plugin for Mermaid.js](http://localhost:3000/vitepress-plugin-mermaid/)
Still localhost.

2022-09-18 16:29 UTC, sidharthv96 commented on docs/integrations.md
> +  - [Plugin for Mermaid.js](http://localhost:3000/vitepress-plugin-mermaid/)
> 1 - Shouldn't we add the root docs to the gitignore file?

We need people to be able to browse the generated docs from github also, with proper rendering. So can't add to gitignore.

> 2 - If you like I can port the current documentation to use vitepress

There are a lot of big changes going in right now, I think we should consider a complete documentation rework once the core things are stable.

2022-09-21 06:10 UTC, merged