Feature/class namespace
mermaid-js/mermaid pull request #4206
Opened 2023-03-09 14:58 UTC by ksilverwall

## :bookmark_tabs: Summary

Brief description about the content of your PR.

Resolves #<your issue id here>

## :straight_ruler: Design Decisions

Describe the way your implementation works or what design decisions you made if applicable.

### :clipboard: Tasks

Make sure you

- [ ] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [ ] :computer: have added unit/e2e tests (if appropriate)
- [ ] :notebook: have added documentation (if appropriate)
- [ ] :bookmark: targeted `develop` branch

2023-03-10 19:47 UTC, sidharthv96 requested changes
@ksilverwall nice work so far, just some minor suggestions. 
@knsv please review the Jison changes.

2023-03-10 19:47 UTC, sidharthv96 commented on packages/mermaid/src/diagrams/class/classDiagram.spec.ts
> +        '}\n';
```suggestion
      const str = `classDiagram
namespace Namespace1 { class Class1 }
namespace Namespace2 { class Class1
}
namespace Namespace3 {
class Class1 {
int : test
string : foo
test()
foo()
}
}
namespace Namespace4 {
class Class1 {
int : test
string : foo
test()
foo()
}
class Class2 {
int : test
string : foo
test()
foo()
}
}`;
```

2023-03-10 19:47 UTC, sidharthv96 commented on packages/mermaid/src/diagrams/class/classDiagram.spec.ts
> +        '}';
Please use ` the same way as the test above.

2023-03-10 19:47 UTC, sidharthv96 commented on packages/mermaid/src/diagrams/class/classTypes.ts
> +};
```suggestion
export interface NamespaceNode {
  id: string;
  domId: string;
  classes: ClassMap;
  children: NamespaceMap;
};
```

2023-03-10 19:47 UTC, sidharthv96 commented on packages/mermaid/src/diagrams/class/classDb.ts
> +  namespaces = {};
```suggestion
  namespaces = {};
  namespaceCounter = 0;
```

2023-03-12 11:51 UTC, ksilverwall commented
@sidharthv96 thank you for your review! I applied all of your suggestions.

2023-03-13 04:04 UTC, ksilverwall commented
@sidharthv96 Thank you for your review! I applied all suggestions.

2023-03-15 03:50 UTC, sidharthv96 commented
@ksilverwall can you avoid force pushing, it's better to have individual smaller commits.

2023-03-15 04:29 UTC, ksilverwall commented
I added the rendering logic

2023-04-14 16:50 UTC, jgreywolf commented
@ksilverwall Resolve the merge conflicts and let get this out there!

2023-04-17 06:44 UTC, ksilverwall commented
@jgreywolf 
I resolved. 🙌

2023-04-25 08:00 UTC, ksilverwall commented
@jgreywolf 
I do not have write-access permission to this repository then I cannot merge.
can you merge this?

2023-04-25 08:18 UTC, sidharthv96 commented
This has significant changes in jison files. Let's wait for a review from @knsv.

2023-04-27 22:06 UTC, aloisklink reviewed
From what I've seen, the changes look great, but I'm not really an expert on SVG/jison code, so I'll let Knut look at that.

**Minor nitpick, the colors of the namespace block seem a bit off** (it's very hard to read the namespace title **BaseShapes**):

![image](https://user-images.githubusercontent.com/19716675/234998779-e2cafe00-ffef-4345-ac22-f8dee5ca168c.png)

Unfortunately, I don't really know much about CSS/SVGs, so I can't tell you how to change the colors (I'm guessing you need to add something here: https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/diagrams/class/styles.js)

The namespace background color should have a sufficient contrast against the namespace text, so that even people with visual impairments (or people viewing Mermaid diagrams outside/with low-quality screens) can read it.

You can use something like https://webaim.org/resources/contrastchecker/ to check whether the colors are okay.

2023-05-01 10:10 UTC, ksilverwall commented
@aloisklink 
Thank you for your review!
I changed namespace rect style with no fill and black border line.

<img width="334" alt="namespace-rect" src="https://user-images.githubusercontent.com/10096645/235439057-7a631a91-e1a7-4390-96c0-aa2f5f7289b2.png">

2023-05-01 13:32 UTC, jgreywolf approved these changes
It is looking good to me. I would like one more review from @knsv on the jison grammar.  Ill bug him about it :)

2023-05-01 16:55 UTC, aloisklink approved these changes
> @aloisklink
> Thank you for your review!
> I changed namespace rect style with no fill and black border line.

**Awesome!** Thanks for making those changes! It even looks good in dark mode: 
![image](https://user-images.githubusercontent.com/19716675/235491660-0a6c0a1e-c93d-4053-87ba-08f0462a4a78.png)

2023-05-01 16:56 UTC, aloisklink commented on packages/mermaid/src/diagrams/class/classRenderer-v2.ts
> +  parent?: string
Fixed by https://github.com/mermaid-js/mermaid/pull/4206/commits/0d373f3a6ab7c8f858b243bfc76677f70b93ade6, thanks @ksilverwall :)

2023-05-03 23:58 UTC, merged