Allow entity diagram attribute names to start with asterisk
mermaid-js/mermaid pull request #4588
Opened 2023-07-03 18:16 UTC by ibrahimWassouf

## :bookmark_tabs: Summary

Attribute name can now start with a leading asterisk to indicate PK

Resolves #4158 

## :straight_ruler: Design Decisions

modified the grep in the parser to allow the asterisk character.

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added unit/e2e tests (if appropriate)
- [ ] :notebook: have added documentation (if appropriate)
- [ ] :bookmark: targeted `develop` branch

2023-07-03 18:42 UTC, ibrahimWassouf commented
While working on this I was wondering if I should make the grep for `ATTRIBUTE NAME` to be like `(\*\s)?[A-Za-z_]...` to allow for the white space between the asterisk and attribute name. I decided against it because I wasn't sure if that would make the rest of the attribute construction confusing, because right now spaces are used to demarcate the different components. Let me know what you think!

2023-07-03 18:57 UTC, tomperr approved these changes

2023-07-06 04:15 UTC, sidharthv96 commented
Hey, the changes look good. But we need corresponding docs changes to let users know that this is supported. 
Also, an imgsnapshottest is required.

2023-07-06 04:16 UTC, sidharthv96 requested changes
Hey, the changes look good. But we need corresponding docs changes to let users know that this is supported.
Also, an imgsnapshottest is required.

2023-07-17 09:35 UTC, merged