[WIP] TeamTopologies diagrams
mermaid-js/mermaid pull request #4678
Opened 2023-07-29 08:19 UTC by Incognito

## :bookmark_tabs: Summary

This PR adds a Team Topologies diagram as per https://github.com/mermaid-js/mermaid/issues/4659 .

Resolves https://github.com/mermaid-js/mermaid/issues/4659

## :straight_ruler: Design Decisions

The grammar accepts a list of teams and team interactions to identify nodes and relationships. That list is later parsed and turned into a layout as per conventions from [Team Topologies](https://teamtopologies.com/)

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [ ] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/development.md#3-update-documentation) is used for all new features.
- [ ] :bookmark: targeted `develop` branch

2023-07-29 08:21 UTC, Incognito commented on packages/mermaid/src/diagrams/team-topology/parser/teamTopology.jison
> +/** mermaid
Please provide feedback on this grammar file. I have not yet added directive support but that would come in the next round of work.

2023-07-29 08:21 UTC, Incognito commented on packages/mermaid/src/diagrams/team-topology/teamTopologyDb.ts
> +import { log } from '../../logger.js';
Please provide feedback on this DB file as I consider it "complete" at the moment.

2023-07-29 08:21 UTC, Incognito commented on packages/mermaid/src/diagrams/team-topology/teamTopologyRenderer.ts
> +export const draw = (txt, id, _version, diagObj) => {
Work on the renderer has not yet started.

2023-07-29 08:31 UTC, Yokozuna59 reviewed
Hi there @Incognito, thanks for you contribution.

If the PR is WIP it would be better to mark it as draft.

And I wouldn't recommend using `tt` as keyword is the best choice, the entity relationship diagram has the `er` keyword, but I guess it's well-known shortcut.

2023-07-29 09:30 UTC, Incognito commented
Thanks @Yokozuna59 , I'll change it to `team-topology` or something more expressive.

2023-07-29 10:44 UTC, Yokozuna59 commented
@Incognito I was referring to mark it as draft, not renaming the title :)

Draft:

![BCF9793C-1763-4CE5-ACCE-983B6F9BBB87](https://github.com/mermaid-js/mermaid/assets/87622592/43ccb2eb-9da1-4105-ac12-bc60d25630ca)

Ready to be merged:

![ADFD1596-C424-40B4-B627-57EE0021409A](https://github.com/mermaid-js/mermaid/assets/87622592/630f0b58-2fd0-491b-9d96-0973f64f1544)

---

The keyword should inline with other keywords:

1. single word (if possible).
2. unique name (shouldn't interfere with other existing diagrams).
3. lowercase (if two words then camelCase.
4. shouldn't have anything not specific to the diagram (trailing `Diagram` or `Chart`, i.e, `classDiagram`)
5. If there is a possible layout difference, add an option after the diagram keyword, i.e., `flowchart TB` (TB means top to bottom layout).

Not really sure what other possible rules we have, those what came to my mind right now.

2023-07-31 09:43 UTC, sidharthv96 requested changes
Hi @Incognito, happy to see a new diagram type addition. 
As @Yokozuna59 noted, the keyword should be `teamTopology`.
Also, the grammar should include the keyword. 

```
teamTopology
  f1#Stream
  f2#Stream
  f1--XaaS->f2
```

I think the grammar requires some more features to support the features mentioned in the website. 

We can continue the grammar discussion in the issue thread.

2023-08-01 09:26 UTC, Incognito commented on packages/mermaid/src/diagrams/team-topology/teamTopologyDiagram.ts
> +// @ts-ignore: TODO Fix ts errors
Marking it unresolved as there are other places in the code we can fix this, I'll handle it in a different PR however, I just want to keep track of it.

2023-08-01 12:12 UTC, Incognito commented on packages/mermaid/src/diagrams/team-topology/parser/teamTopology.jison
> +/** mermaid
I've removed support for this boilerplate from the DB.

I've raise a new PR to remove directives from the documentation: https://github.com/mermaid-js/mermaid/pull/4688

2023-08-01 12:18 UTC, sidharthv96 commented on packages/mermaid/src/diagrams/team-topology/teamTopologyDb.ts
> +let interactions = {};
You'll have to add Interfaces and use them here. 

Reference: https://github.com/mermaid-js/mermaid/blob/bac717813bdc2fc7194d05e5295c367102ad5b7c/packages/mermaid/src/diagrams/class/classDb.ts#L28-L33

2023-08-01 12:21 UTC, Incognito commented on packages/mermaid/src/diagrams/team-topology/teamTopologyDetector.ts
> +const id = 'tt';
Only this one spot or should beta suffix cascade into other parts of the code?

2023-08-01 12:33 UTC, Incognito commented on packages/mermaid/src/diagrams/team-topology/teamTopologyDiagram.ts
> +// @ts-ignore: TODO Fix ts errors
fyi: https://github.com/mermaid-js/mermaid/pull/4689

2023-08-01 12:42 UTC, Incognito commented
Acted on most feedback above.

Topics still outstanding:
1. Adding types
2. Support for quotes, team names with whitepsace
3. Unicode team names, markdown team names
5. Diagram renderer
6. Diagram docs

Any feedback on other topics is open, and if there's support from anyone on how to proceed with any of the above I'm more than happy to collaborate with anyone spontaneously (I can only push this topic along in limited bursts of free time).

2023-08-02 05:43 UTC, sidharthv96 commented on packages/mermaid/src/diagrams/team-topology/teamTopologyDetector.ts
> +const id = 'tt';
https://github.com/mermaid-js/mermaid/issues/4459

Can you please add this to the new diagram documentation too?

2024-01-15 23:11 UTC, mrueg commented
@Incognito do you have any plans to continue on this PR?

2024-01-25 09:58 UTC, Incognito commented
@mrueg Thanks for checking in. Yes I'd love to, my main constraint is really just my time however. When things slow down a bit I have space to push this, but the last few months have been pretty busy on my end.

Happy to close it for now if having it open is distracting from the project's focus. I can re-open once it is ready for another round of review. Or we can keep it open. Your call :)

2024-01-25 15:10 UTC, mrueg commented
@Incognito Understood, no need to close it from my perspective. I just wanted to check if that's something you still plan to work on (otherwise I'd try to take a look at when I get time)

2025-02-15 11:53 UTC, closed without merging