3326 gantt improve links
mermaid-js/mermaid pull request #4695
Opened 2023-08-02 18:14 UTC by ykatchou

## :bookmark_tabs: Summary

In order to all links within gantt chart to open in a new tab (or allow a new target) i did add the target options to links.

Resolves #3326 

## :straight_ruler: Design Decisions

As discussed in the issue #3326 , i did base my change on the changes done on flowchart in #1585.
I did limit the usage of target to the main case of a simple url.

As I’m not a js dev, i did start from a "clean" env.
To make the dev env works, I did need to do some slight changes.
Those changes were done in a dedicated commit (the first one) :
- I did add the tsx package to handle compatibility issues with ts-node-esm.
- I needed to run pnpm from npx.

Those changes were done in a dedicated commit (the first one), feel free to revert those.
  
### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added necessary unit/e2e tests.
- [x] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/development.md#3-update-documentation) is used for all new features.
- [x] :bookmark: targeted `develop` branch

2023-08-10 22:29 UTC, sidharthv96 commented on packages/mermaid/package.json
> +    "types:verify-config": "tsx scripts/create-types-from-json-schema.mts --verify",
Can you please move the changes related to npx and tsx to another PR?
We've had issues when using tsx in the past.

2023-08-10 22:35 UTC, sidharthv96 requested changes
Nice work!

I think we can keep the syntax simpler by sticking to how other diagrams support targets. There's no need to support with and without quotes.

2023-08-10 22:35 UTC, sidharthv96 commented on packages/mermaid/src/diagrams/gantt/ganttDb.js
> +      links[id] = [linkStr, target];
Don't use arrays, use objects, so it's clear when using the values. 

```
      links[id] = {link: linkStr, target};
```

2023-08-10 22:35 UTC, sidharthv96 commented on packages/mermaid/src/diagrams/gantt/parser/gantt.jison
> +
```
"_self"                  return 'LINK_TARGET';
"_blank"                 return 'LINK_TARGET';
"_parent"                return 'LINK_TARGET';
"_top"                   return 'LINK_TARGET';
```

This is from flow.jison. 

Why do we need the duplicates with escaped quotes?

2023-09-06 17:32 UTC, sidharthv96 commented
@ykatchou waiting for your updates

2024-10-18 15:17 UTC, annabel commented
@ykatchou 👋 Hi! Do you think you'll have time to update this with the suggested  changes any time soon?

2026-06-01 11:58 UTC, closed without merging