feat(er): add entity name alias
mermaid-js/mermaid pull request #4758
Opened 2023-08-21 21:36 UTC by tomperr

## :bookmark_tabs: Summary

Allow to add an alias to entity name

Resolves #4746 

## :straight_ruler: Design Decisions

Update parser to handle `as` keyword
Update renderer to show the alias if it exists

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added necessary unit/e2e tests.
- [x] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/development.md#3-update-documentation) is used for all new features.
- [x] :bookmark: targeted `develop` branch

2023-08-22 06:27 UTC, sidharthv96 commented
I think we should use the existing mermaid format to add aliases. 
In class, flow, etc. `id["text"]` format is used. 

So, in ER, that would be.

```
erDiagram
  cc["Credit Card"] {
    varchar(16) number
    ...
  }
  cc 1+ -- 1 account
```

2023-08-22 10:47 UTC, sidharthv96 approved these changes
Wonderful!
Can you also add a test in cypress/integration/rendering/erDiagram.spec.js, so we can ensure the rendering works? Thank you!

2023-08-22 11:42 UTC, tomperr commented
woops sorry this last test is not perfect

2023-08-22 11:54 UTC, tomperr commented
should be good now

2023-08-22 11:57 UTC, tomperr commented
Btw, we should consider migrating ER diagram (and some others) from JS to TS. I don't know if there is already an issue about it

2023-08-22 13:04 UTC, sidharthv96 commented
> Btw, we should consider migrating ER diagram (and some others) from JS to TS. I don't know if there is already an issue about it

Yes. @Yokozuna59 has been standardizing diagrams. [PRs](https://github.com/mermaid-js/mermaid/pulls?q=is%3Apr+author%3AYokozuna59+is%3Aclosed)

If you can get started with ER in a different PR (this one is ready to be merged), that would be great.

2023-08-22 13:15 UTC, Yokozuna59 commented
> Btw, we should consider migrating ER diagram (and some others) from JS to TS. I don't know if there is already an issue about it

There is an open issue about the structure we're following, #4499. It is not finished and kind of outdated, but you can refer to it. Feel free to give any feedback or ask for help with it.

2023-08-23 15:13 UTC, nirname commented
Please, wait for me, I'll do a review on this ASAP

2023-08-24 07:28 UTC, sidharthv96 commented on packages/mermaid/src/diagrams/er/erRenderer.js
> +      .text(entities[entityName].alias || entityName);
Although it doesn't matter much in this case, it's better to always use `??` instead of `||` to avoid unexpected bugs.

2023-08-24 09:53 UTC, nirname requested changes
Something went wrong

---

Person has to be called "Customer" but is not

```
---
title: Not Working
---
erDiagram
  Person ||--o{ Order : "has many"
  Person["Customer"] {
    string name
  }
```

While changing the order of the statements does the trick

```
---
title: Working
---
erDiagram
  Person["Customer"] {
    string name
  }
  Person ||--o{ Order : "has many"
```

---

<img src="https://github.com/mermaid-js/mermaid/assets/2842432/65712f7d-434b-496d-a7f5-4bbe0b0acbd0" width=300/>
<img src="https://github.com/mermaid-js/mermaid/assets/2842432/1740c3e7-8a9d-4f19-8c00-f28a995db653" width=300/>

---

A couple of tests to cover the case would be nice

2023-08-24 10:39 UTC, tomperr commented
Nice catch, I will take a look ASAP

2023-08-24 19:30 UTC, nirname commented
@tomperr I see some commits from you addressing our comments. Please, ask re-review when it is ready

2023-08-25 04:25 UTC, sidharthv96 commented
Some cache in netlify is preventing the generation of updated site.
Clearing cache from their dashboard built the right version. Now we can test the changes using the deploy preview link.

2023-08-26 11:01 UTC, nirname approved these changes

2023-08-26 11:07 UTC, merged