3952 - lexical ids
mermaid-js/mermaid pull request #4785
Opened 2023-08-28 11:44 UTC by jgreywolf

## :bookmark_tabs: Summary

Changed ids of edge paths for relationships to use class names for easier identification in code

Resolves #3952
![image](https://github.com/mermaid-js/mermaid/assets/300077/5669e9f0-ac8e-4b63-aab0-1ac8142dd6e5)

2023-09-06 07:53 UTC, sidharthv96 requested changes

2023-09-06 07:53 UTC, sidharthv96 commented on packages/mermaid/src/diagrams/class/classRenderer-v2.ts
> +      id: 'id_' + edge.id1 + '_' + edge.id2,
Is this the only relevant part for lexical IDs?
If so, can you reset your branch to develop and only have this in the PR?

2023-09-06 07:56 UTC, sidharthv96 commented on packages/mermaid/src/diagrams/class/classRenderer-v2.ts
> +      id: 'id_' + edge.id1 + '_' + edge.id2,
I think the cnt should also be in the ID. 

Otherwise, id of [a, b_c] and [a_b, c] will both be id_a_b_c, leading to a conflict.

2023-09-20 23:35 UTC, jgreywolf commented
will resubmit

2023-09-20 23:35 UTC, closed without merging