Made script to convert directives to yml
mermaid-js/mermaid pull request #4827
Opened 2023-09-10 06:39 UTC by Aryangp

## :bookmark_tabs: Summary

I have created a script that will convert the existing directive code to yml code as it scan throught the given file and change it to yml code

Resolves #4756

## :straight_ruler: Design Decisions

I have used simple fs library to scan througth the file and using regex pattern to find the directives in it when i find those pattern i make a function that take the json code and convert it into yml and that write that changed code in the existing file 

### :clipboard: Tasks

Make sure you

- [ ] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [ ] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/development.md#3-update-documentation) is used for all new features.
- [ ] :bookmark: targeted `develop` branch

2023-09-10 20:01 UTC, Yokozuna59 requested changes

2023-09-10 20:01 UTC, Yokozuna59 commented on docs/syntax/script_yml/convertDirectivesToYml.ts
> +       const newYamlContent=`{"config":${jsonContent}}`;
And some data aren't inside `config. Please refer to docs for that.

2023-09-11 07:06 UTC, Aryangp commented on docs/syntax/script_yml/convertDirectivesToYml.ts
> +    const diresctiveRegix=/%%{init:(.*?)\}%%/g;
ok but we have  every directive with init in it so that is why i used this regex pattern

2023-09-11 07:06 UTC, Aryangp commented on docs/syntax/script_yml/convertDirectivesToYml.ts
> +    }
ok i will do this  change thanks

2023-09-11 07:06 UTC, Aryangp commented on docs/syntax/script_yml/convertDirectivesToYml.ts
ok sure

2023-09-11 07:07 UTC, Aryangp commented on docs/syntax/script_yml/convertDirectivesToYml.ts
> +       const newYamlContent=`{"config":${jsonContent}}`;
can you elaborate this one as i am not able to understand the data part please

2023-09-11 11:44 UTC, nirname requested changes
Please, fix linting.
If this request only adds script, but does not update directives, then it should not resolve the issue

2023-09-11 11:44 UTC, nirname commented on docs/syntax/script_yml/convertDirectivesToYml.ts
> +    const diresctiveRegix=/%%{init:(.*?)\}%%/g;
Not necessarily, there are some other samples. It also can have empty spaces between after `%%{`, so do not rely on its content.

This one is escaped `\}`, but this one is not `{` (probably, should be).

2023-09-11 11:44 UTC, nirname commented on docs/syntax/script_yml/convertDirectivesToYml.ts
> +       const newYamlContent=`{"config":${jsonContent}}`;
As the example I provided in the issue:

```
title: This is another complicated flow
config:
  theme: base
  sankey:
    nodeAlignment: justify
  flowchart:
    curve: cardinal
    htmlLabels: false
```
Not everything is under the `config` key

2023-09-11 14:48 UTC, sidharthv96 commented
Please add the modified contents to this PR.
So we can validate the output and see if we miss anything.

2023-09-12 17:30 UTC, Aryangp commented on docs/syntax/script_yml/convertDirectivesToYml.ts
> +       const newYamlContent=`{"config":${jsonContent}}`;
hi can you help me with a regex patter that i can use to solve this above example and like can you give a directive example where above mentioned example is converted from

2023-09-13 04:07 UTC, Aryangp commented on docs/syntax/script_yml/convertDirectivesToYml.ts
> +       const newYamlContent=`{"config":${jsonContent}}`;
hi @Yokozuna59  can you provide me the link where data is not inside config  and also the pie that you mentioned will come automatically  can you help me out with it

2023-09-13 10:34 UTC, nirname commented on docs/syntax/script_yml/convertDirectivesToYml.ts
> +       const newYamlContent=`{"config":${jsonContent}}`;
@aloisklink we need your help. There is a [schema which represents config](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/schemas/config.schema.yaml), but it seems that the config is only a subset of yaml directives. Where to look, to have a full example?

@Aryangp 
There is a [schema which represents config](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/schemas/config.schema.yaml). According to the docs we have [`config` and `title` keys (at least)](https://mermaid.js.org/config/configuration.html)

[Directives](https://mermaid.js.org/config/directives.html) is what is being deprecated.

Addressing your question about syntax. These were recently removed from grammar, but you can get the idea
of w[hat directives syntax was](https://github.com/mermaid-js/mermaid/pull/4759/files#diff-f796aa757eb63573c71990c5afda198a9da08f0ef0d096e03558ecf8c7291c80L27-L35) and [what the current function to detect them is](https://github.com/sidharthv96/mermaid/blob/45788f86971877d9be0bb173e25c8be3968028e8/packages/mermaid/src/utils.ts#L130)

There is [an example of detect function call](https://github.com/mermaid-js/mermaid/pull/4759/files#diff-bd6877d3c484a46c0054c3b3c3e41d176e4a37423c88304836e69a06af10beceR164)

This is how [diagrams are preprocessed](https://github.com/mermaid-js/mermaid/pull/4759/files#diff-ddaacbd7f424d601af4ba9ababb50fb63a50ec52afb0f908ad05f9eb990d6167)

2023-09-14 02:36 UTC, aloisklink commented on docs/syntax/script_yml/convertDirectivesToYml.ts
> +       const newYamlContent=`{"config":${jsonContent}}`;
> @aloisklink we need your help. There is a [schema which represents config](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/schemas/config.schema.yaml), but it seems that the config is only a subset of yaml directives. Where to look, to have a full example?

So far, I don't think there isn't anything, see https://github.com/mermaid-js/mermaid/issues/4757. There's only the https://mermaid.js.org/config/configuration.html#frontmatter-config documentation, which isn't very substantial.

Contributions to improving the documentation are welcome (even I don't know what can and can't be put into frontmatter, e.g. does `wrap: true` do anything??)

Long-term, I'd love to make a JSON Schema that represents and documents the front matter, but I haven't had much time recently to work on mermaid unfortunately (and I first want to help improve the existing `MermaidConfig` JSON schema).

2023-09-16 01:19 UTC, nirname commented on docs/syntax/script_yml/convertDirectivesToYml.ts
> +       const newYamlContent=`{"config":${jsonContent}}`;
@Aryangp please keep `title` and `config` keys. I'm not sure what else should be here

2023-11-03 04:05 UTC, Aryangp commented
@Yokozuna59  No sorry actually i had my university exams can you give me two days i will update the changes in the PR

2024-06-20 14:41 UTC, nirname commented
@Aryangp ping

2025-04-18 08:17 UTC, closed without merging