fix(tooltip): remove redundant scroll offset
mermaid-js/mermaid pull request #4958
Opened 2023-10-19 15:03 UTC by csholmq

## :bookmark_tabs: Summary

window.scrollY is already account for which means document.body.scrollTop incorrectly offsets the tooltip vertically.
The same is not true for horizontal position.

## :straight_ruler: Design Decisions

Removing one of the scroll offsets should set things straight. Not tested as I don't know how to.

### :clipboard: Tasks

Make sure you

- [ ] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [ ] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/development.md#3-update-documentation) is used for all new features.
- [x] :bookmark: targeted `develop` branch

2023-10-20 06:43 UTC, csholmq commented
Tested manually on a rendered page.

Before scrolling:
![image](https://github.com/mermaid-js/mermaid/assets/1297882/33ec4678-a931-43f0-9b55-c20b839dd84c)

After scrolling:
![image](https://github.com/mermaid-js/mermaid/assets/1297882/877c1131-8d68-4cd5-86b3-e18a5d7a836e)

---

After fixes (despite scrolling):
![image](https://github.com/mermaid-js/mermaid/assets/1297882/5d920edd-d0e6-422c-bebe-2ad370c5be33)

2023-10-31 06:46 UTC, sidharthv96 requested changes
Love to see a magic number disappear.

2023-10-31 06:46 UTC, sidharthv96 commented on packages/mermaid/src/diagrams/flowchart/flowDb.js
> +        .style('top', window.scrollY + rect.top + (rect.bottom - rect.top) + 'px');
If the bracket is opened, it simplifies to this. 
Any reason we can't use it?

```suggestion
        .style('top', window.scrollY + rect.bottom  + 'px');
```

2023-11-01 06:15 UTC, csholmq commented
@sidharthv96 I have no idea why the linting job failed. Doesn't seem to complain over actual linting but something with the setup.

2023-11-09 08:51 UTC, sidharthv96 commented
The lint was failing because there was an unnecessary space in the changes.  I've fixed it.

2023-11-09 09:06 UTC, merged