Matrix Chart
mermaid-js/mermaid pull request #5165
Opened 2023-12-27 07:12 UTC by harishkumarc

## :bookmark_tabs: Summary

Solution for the issue (Diagram proposal: N x M matrix ) #5136 

Resolves #5136

## :straight_ruler: Design Decisions

Describe the way your implementation works or what design decisions you made if applicable.

### :clipboard: Tasks

Make sure you

- [ ] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [ ] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/development.md#3-update-documentation) is used for all new features.
- [ ] :bookmark: targeted `develop` branch

2023-12-27 08:39 UTC, harishkumarc commented
diagram looks like below image 

![image](https://github.com/mermaid-js/mermaid/assets/10988763/f771aca2-b7a4-48ef-bc4e-69c79ce21c70)

2024-01-14 16:39 UTC, nirname commented
Hi! Awesome job. Is this still under progress?

2024-01-14 17:03 UTC, nirname requested changes
Just a work-in-progress note. Diagram had been copied from XY, and in case new diagram's syntax and behavior inherits so many features from XY, perhaps we should consider to extend XY.

Documentation needs to be updated as well. Examples provided do not work, unfortunately.

Nevertheless this is a good first approach. I hope it will evaluate and is not abandoned, looking forward for new updates

2024-01-14 17:05 UTC, nirname commented
@harishkumarc Because it is not in its final state I'll convert this PR to a draft. Feel free to mark it as ready for review, when needed.

2024-01-15 10:50 UTC, harishkumarc commented
> Hi! Awesome job. Is this still under progress?

Thank you, I need to write test cases and polish the component a little bit

2024-01-15 10:52 UTC, harishkumarc commented
> Just a work-in-progress note. Diagram had been copied from XY, and in case new diagram's syntax and behavior inherits so many features from XY, perhaps we should consider to extend XY.
> 
> Documentation needs to be updated as well. Examples provided do not work, unfortunately.
> 
> Nevertheless this is a good first approach. I hope it will evaluate and is not abandoned, looking forward for new updates

Yes, I copied most of the code from XY chart and have done some significant change in the functionality so i would recommend keeping it as a separate chart for now

2024-01-15 10:52 UTC, harishkumarc commented
> @harishkumarc Because it is not in its final state I'll convert this PR to a draft. Feel free to mark it as ready for review, when needed.

sure, not a problem

2024-01-15 10:53 UTC, harishkumarc commented on packages/mermaid/src/diagrams/matrixchart/parser/matrixchart.jison
> +%%
I will finish the rest of the comments you have mentioned and you can evaluate again if it is good to extend the XY chart, thanks

2024-01-15 10:53 UTC, harishkumarc commented on packages/mermaid/src/docs/intro/examples.md
> +### [XY Chart](../syntax/matrixChart.md)
sure

2024-01-15 10:54 UTC, harishkumarc commented on packages/mermaid/src/docs/syntax/matrixChart.md
> +> It's important to note that while the current implementation of mermaid-js includes these two chart types, the framework is designed to be dynamic and adaptable. Therefore, it has the capacity for
sure

2024-01-15 11:02 UTC, nirname commented
@mermaid-js/atlantians Any thoughts on this one?

2026-04-21 10:11 UTC, knsv commented
Hi, and thanks for the effort you put into this PR. As part of some general housekeeping we're going through older draft PRs and closing ones that have been sitting idle for a while: this is purely to keep the queue manageable, not a judgment on the contribution. If you'd like to continue this work, you're very welcome to reopen the PR or open a new one based on current `develop`: we'll gladly take another look. Really appreciate you taking the time to contribute to Mermaid!

2026-04-21 10:11 UTC, closed without merging