Resolved issue with subgraph configuration
mermaid-js/mermaid pull request #5183
Opened 2024-01-07 12:11 UTC by rowanfr

## :bookmark_tabs: Summary

This commit resolves the issues with subgraph configuration, specifically for `nodeSpacing` and `rankSpacing`. This commit additionally adds an example graph to the `flowchart.html` to demonstrate this resolution.

Resolves #3258

## :straight_ruler: Design Decisions

This is a fairly simple modification that applies the configuration held in the label for the overall graph to the configuration for the cluster/subgraph in order to ensure they have matching configurations. This is done right before `recursiveRender` begins to render each cluster. The reason this needs to be done is that `recursiveRender` will use the default settings for any seemingly new or unlabeled graph. As clusters/subgraphs are considered unlabeled graphs by default this causes a mismatch in configurations for the chart overall and the subgraph. Therefore if one adds the graph label right before rendering it resolves the mismatch of configurations.

Some potential improvements for this commit would be to allow subgraphs to have there own customization labels. This would be fairly trivial (presumably) by just replacing `graph.graph()` with whatever settings you want from whatever configurations you want.

### :clipboard: Tasks

Make sure you

- [X] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [ ] :computer: have added necessary unit/e2e tests. (Not necessary to my knowledge though I'm open to alternative opinions)
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/development.md#3-update-documentation) is used for all new features. (Not necessary to my knowledge as this is a bugfix)
- [X] :bookmark: targeted `develop` branch

2024-01-14 20:08 UTC, nirname requested changes
Hi! Thanks for addressing the issue! Deployment failed, we will have to investigate why, but regardless of this there are some minor comments.

2024-01-14 20:08 UTC, nirname commented on demos/flowchart.html
> +      %%{init:{'flowchart':{'nodeSpacing': 1, 'rankSpacing':'1'}}}%%
Avoid directives configuration, which is obsolete, use frontmatter
```suggestion
      ---
      title: Subgraph nodeSpacing and rankSpacing example
      config:
        flowchart:
          nodeSpacing: 1
          rankSpacing: 1
      ---
```

2024-01-14 23:15 UTC, rowanfr commented
@nirname Thanks for the suggested change in syntax, I didn't even know that was available

2024-01-19 17:14 UTC, sidharthv96 commented
@rowanfr there are multiple failing tests. 

![Flowchart-v2-57-handle-nested-subgraphs-with-outgoing-links-4 diff](https://github.com/mermaid-js/mermaid/assets/10703445/e34cc703-90aa-4cc0-b055-e143a74b4ed8)
![Flowchart-v2-66-More-nested-subgraph-cases-(TB) diff](https://github.com/mermaid-js/mermaid/assets/10703445/66ef01b9-7b73-4267-b701-38f23e680aec)
![Flowchart-v2-67-More-nested-subgraph-cases-(RL) diff](https://github.com/mermaid-js/mermaid/assets/10703445/e1f088cb-4f5e-434a-8386-1fe17d2eab06)
![Flowchart-v2-68-More-nested-subgraph-cases-(BT) diff](https://github.com/mermaid-js/mermaid/assets/10703445/79f062c8-bda3-4245-93dc-ef61f3965531)
![Flowchart-v2-69-More-nested-subgraph-cases-(LR) diff](https://github.com/mermaid-js/mermaid/assets/10703445/26962665-31ad-48d9-800b-3e36a080f2c5)
![Flowchart-v2-2050-handling-of-different-rendering-direction-in-subgraphs diff](https://github.com/mermaid-js/mermaid/assets/10703445/2b4e13fc-a91b-4645-b280-4d1852e164db)
![Flowchart-v2-Subgraph-title-margins-Should-render-subgraphs-with-title-margins-and-edge-labels diff](https://github.com/mermaid-js/mermaid/assets/10703445/a6203d25-a2c1-474b-b64a-baae7172a013)
![Flowchart-v2-Subgraph-title-margins-Should-render-subgraphs-with-title-margins-set-(LR)-and-htmlLabels-set-to-false diff](https://github.com/mermaid-js/mermaid/assets/10703445/1aa251bf-6563-41a5-822f-9b21fc372924)
![Flowchart-v2-Subgraph-title-margins-Should-render-subgraphs-with-title-margins-set-(LR) diff](https://github.com/mermaid-js/mermaid/assets/10703445/5f8f56c5-0422-4270-94dd-781047ff981f)
![Flowchart-v2-Subgraph-title-margins-Should-render-subgraphs-with-title-margins-set-(TD) diff](https://github.com/mermaid-js/mermaid/assets/10703445/3f21dab2-e210-44d1-be6b-9ff7f93156de)
![Graph-30-Possibility-to-style-text-color-of-nodes-and-subgraphs-as-well-as-apply-classes-to-subgraphs diff](https://github.com/mermaid-js/mermaid/assets/10703445/e551c314-f9ed-4cbd-9f87-d671e05b1f41)
![Graph-64-fontawesome-icons-in-edge-labels diff](https://github.com/mermaid-js/mermaid/assets/10703445/2cfcb263-c793-45f2-a811-ec56947182ee)
![Flowchart-v2-63-title-on-subgraphs-should-be-themable diff](https://github.com/mermaid-js/mermaid/assets/10703445/cb79aa9b-7310-4402-98c4-232e0e785605)
![Flowchart-v2-52-handle-nested-subgraphs-in-several-levels diff](https://github.com/mermaid-js/mermaid/assets/10703445/9824e9e6-61d3-4939-9582-306ea8ce05b0)
![Flowchart-v2-53-handle-nested-subgraphs-with-edges-in-and-out diff](https://github.com/mermaid-js/mermaid/assets/10703445/832c6e4a-9860-4a9c-af09-62eaf8c80eed)
![Flowchart-v2-57-handle-nested-subgraphs-with-outgoing-links-2 diff](https://github.com/mermaid-js/mermaid/assets/10703445/9cf83eca-6119-4be2-a62a-b53176a239ea)
![Flowchart-v2-55-handle-nested-subgraphs-with-outgoing-links-2 diff](https://github.com/mermaid-js/mermaid/assets/10703445/fd5bb72e-8b9d-40f2-8a09-d52241971640)

2024-01-20 01:02 UTC, rowanfr commented
@sidharthv96 Could you tell me how or where you encountered the errors that your showing? I'm using the dev server to get output data and they all seem to be resolving as expected.
![image](https://github.com/mermaid-js/mermaid/assets/28838223/61bcdc19-1df1-456e-8890-ce60063be2fd)

2024-01-20 02:24 UTC, sidharthv96 commented
It was observed after the run of the E2E test that was triggered by the pull request event (not the push event).

2024-01-20 02:53 UTC, rowanfr commented
After some research the e2e test failing only doesn't seem to occur locally outside of randomly when changing the window or running other applications, however Cypress errors for `rendering/flowchart-v2.spec.js` and `rendering/flowchart.spec.js` don't occur locally on Firefox Nightly or Electron after testing. I think this means that the tests are configured to take snapshots too early, but I'm still investigating it.

2024-01-20 03:35 UTC, rowanfr commented
For the examples above all seem to have the links and graphs shift position slightly. This seems to be an browser dependent issue as I can test locally on electron it repeatedly produce successful graphs for Cypress, firefox nightly seems to randomly produce successful graphs while edge and chrome do not. As I've stated earlier I'll look into this a bit further but I think this has to do with browser rendering diff, which I don't have the ability to address

2024-01-22 14:10 UTC, sidharthv96 commented
Hmm, The E2E tests are working fine on other PRs, so it means some change in this one is triggering the browser inconsistency, and it's failing consistently as well, not flaky. 

Maybe your change has some other effects downstream that's causing the issue. We'll have to investigate further. 

@aloisklink @nirname @Yokozuna59 do you folks have any pointers?

2024-02-28 19:14 UTC, aloisklink requested changes
I think I've spotted the issue that was causing the E2E tests to fail, we just need to slightly modify the code so that it doesn't copy the parent graph's margin.

It would also be nice to have a very basic E2E test in the [cypress/integration/rendering/flowchart-v2.spec.js](https://github.com/mermaid-js/mermaid/blob/d6e738ac4cf2e208326b0ca3a8702d940cb846ec/cypress/integration/rendering/flowchart-v2.spec.js) file (e.g. your demo diagram), just so we get automated tests so we know not to break your feature!

Other than that, this PR looks good to me.

2024-02-28 19:14 UTC, aloisklink commented on packages/mermaid/src/dagre-wrapper/index.js
> +        node.graph.setGraph({ ...graph.graph(), rankdir: node.graph.graph().rankdir });
I think I've found the issue that was causing the screenshots of the E2E tests to fail.

The issue is that we were updating `marginy` for subgraphs to use their parent value, and that was causing the positioning to shift very slightly.

If we instead only copy over the `ranksep` (i.e. the [`rankSpacing`](https://mermaid.js.org/config/schema-docs/config-defs-flowchart-diagram-config.html#rankspacing)) and the `nodesep` (i.e. the [`nodeSpacing`](https://mermaid.js.org/config/schema-docs/config-defs-flowchart-diagram-config.html#nodespacing)), it seems to work fine.

In the real world, however, it should would slightly modify the subgraphs of anybody that has set `rankSpacing`/`nodeSpacing`, so IMO, this should be in a MINOR release, not a PATCH release.

```suggestion
        const { ranksep, nodesep } = graph.graph();
        node.graph.setGraph({
          ...node.graph.graph(),
          ranksep,
          nodesep,
        });
```

2024-02-28 19:14 UTC, aloisklink commented on demos/flowchart.html
> +      end
Awesome for adding a demo!

Can you also add this demo (or another diagram) to the [`cypress/integration/rendering/flowchart-v2.spec.js`](https://github.com/mermaid-js/mermaid/blob/d6e738ac4cf2e208326b0ca3a8702d940cb846ec/cypress/integration/rendering/flowchart-v2.spec.js) file? This is just so we get some automated screenshots of the new feature you added :)

It should look something like:

```ts
  it('Should render subgraphs with different nodeSpacing', () => {
    imgSnapshotTest(`---
title: Subgraph nodeSpacing and rankSpacing example
---
flowchart LR
  X --> Y
  subgraph X
    direction LR
    A
    C
  end
  subgraph Y
    direction LR
    B
    D
  end
`,
      { flowchart: { nodeSpacing: 1, rankSpacing: 1 } }
    );
  });
```

2024-02-29 01:44 UTC, rowanfr commented
@aloisklink Thanks for spotting the issue that was causing the E2E tests to fail. That problem genuinely had me completely stumped for months. I've added the E2E testing for subgraph configuration as you suggested

2024-02-29 11:04 UTC, aloisklink approved these changes
Looks awesome to me now! Btw, I've slightly adjusted the PR title, let me know if you don't like it and want to change it back (or to something else).

> Thanks for spotting the issue that was causing the E2E tests to fail. That problem genuinely had me completely stumped for months.

Yep, the `dagre-wrapper/index.js` file is really really hard to read. I really want to look into converting it to TypeScript and adding at least some documentation to it, but I think we might also need to fix some types in a third-party library (and that library is also very undocumented), so it would be a lot of work :(

2024-02-29 12:09 UTC, rowanfr commented
The new title looks great and is more accurate to the solution, the earlier title was generally what was desired so the change to it makes sense. 

As for `dagre-wrapper/index.js` I agree that unraveling that back to third party libraries that eventually rely on `graphlib` graph labels for rendering logic was fairly difficult and TypeScript alongside further documentation of the third party libraries would go a long way to help

2024-02-29 12:51 UTC, rowanfr commented
The E2E tests are failing due to some separate git graph tests that were failing due to randomized commit IDs as detailed in the issue #5343 and the subsequent PR #5344. If we merge those changes minor changes the E2E testing for this PR should be resolved.

2024-03-01 03:21 UTC, rowanfr commented
@nirname could you check over the changes you've requested to see if they've been completed and then approve the PR if you feel confident?

2024-03-12 18:24 UTC, Stevio54 commented
Is there an update to this pull request, I am having the same issues and would love a solution :)

2024-03-12 19:16 UTC, rowanfr commented
@Stevio54 It's feature complete, it just needs to be merged

2024-03-23 12:09 UTC, merged