Update classId generation to use generic type
mermaid-js/mermaid pull request #5223
Opened 2024-01-22 19:25 UTC by jgreywolf

## :bookmark_tabs: Summary

In order to allow class diagrams where there are multiple generic classes with the same name, only different type parameter, updated the classId generation logic to append `-TYPE` to the end of class name to get the id. 

However, this means that any later referrals to that class needs to either be in the format `class~T~` or `class-T` to ensure that the correct class is utilized.

- Updated documentation
- added tests

Resolves #4762 

## :straight_ruler: Design Decisions

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added necessary unit/e2e tests.
- [x] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/contributing.md#update-documentation) is used for all new features.
- [x] :bookmark: targeted `develop` branch

2024-01-23 05:19 UTC, sidharthv96 requested changes
Nice! This should help out a lot of people.

Is this a breaking change though? (Or did the previous implementation not support this at all?)
Should we fall back to previous behavior, so existing diagrams don't break? 

If the diagram refers class without type, we could pick whichever class was defined first (or whatever the current behaviour is)?

We need rendering tests as well. 

cc @knsv

2024-01-23 05:19 UTC, sidharthv96 commented on packages/mermaid/src/diagrams/class/classDb.ts
> +  return { classId: classId, className: className, type: genericType };
```suggestion
  return { classId, className, type: genericType };
```

2024-01-23 05:19 UTC, sidharthv96 commented on packages/mermaid/src/docs/syntax/classDiagram.md
> +```
<img width="1440" alt="image" src="https://github.com/mermaid-js/mermaid/assets/10703445/0ad4940b-9825-446b-b2dc-82e252afd3ae">

Example throws error

2024-01-27 20:21 UTC, jgreywolf commented on packages/mermaid/src/docs/syntax/classDiagram.md
> +```
Fixed

2024-01-27 20:21 UTC, jgreywolf commented
> Nice! This should help out a lot of people.
> 
> Is this a breaking change though? (Or did the previous implementation not support this at all?) Should we fall back to previous behavior, so existing diagrams don't break?
> 
> If the diagram refers class without type, we could pick whichever class was defined first (or whatever the current behaviour is)?
> 
> We need rendering tests as well.
> 
> cc @knsv

The previous implemetation did not support this at all.  This should not be a breaking change, any existing class diagrams will still parse the same as they did before

2024-01-28 18:19 UTC, jgreywolf commented
> We need rendering tests as well.

There are already rendering tests that cover use of generic in class name

2024-01-29 15:56 UTC, jgreywolf commented
@sidharthv96 
FYI - in reviewing the failing rendering tests, these are actually expected, since this is fixing a bug and the previous renders were actually not showing the correct data

This is assuming that the test result images are showing the old (expected) on the left, and the new (received) is on the left

2024-01-29 16:00 UTC, sidharthv96 commented
That's fine. Yes it's like you mentioned.

2024-03-23 13:09 UTC, sidharthv96 requested changes
> The previous implemetation did not support this at all. This should not be a breaking change, any existing class diagrams will still parse the same as they did before

Consider this diagram
```
classDiagram
    class Class01~T~
      Class01 : size()
      Class01 : int chimp
      Class01 : int gorilla
      Class08 <--> C2: Cool label
      class Class10~T~ {
        &lt;&lt;service&gt;&gt;
        int id
        test()
      }
```

In mermaid.live
<img width="488" alt="image" src="https://github.com/mermaid-js/mermaid/assets/10703445/31145587-86bb-4f68-8702-6d6a67a8eb9f">

In branch preview
<img width="877" alt="image" src="https://github.com/mermaid-js/mermaid/assets/10703445/8c5d5c73-4cf6-4097-b7cd-137bd6b215fd">

So this infact breaks existing diagrams. So we should add a fallback so the diagram will render the same.

2024-11-08 17:40 UTC, jgreywolf commented
FYI - I am redoing this slightly as part of a separate PR (too many conflicts).  Im not sure this is the best solution anymore either. I mentioned to someone else recently, that I totally regret using `~~` to denote types.

2024-11-08 17:40 UTC, closed without merging