feat(git-graph): GitGraph Bottom-to-Top Orientation
mermaid-js/mermaid pull request #5259
Opened 2024-02-03 03:00 UTC by JingyuMarcelLee

feat(git-graph): GitGraph BT feature:

## :bookmark_tabs: Summary

Added Bottom-to-Top orientation for the gitGraph. Added ```B``` to ```gitGraph.jison``` under ```"DIR"``` token and tested this at ```gitGraphParser.spec.js```.  Made changes to the ```gitGraphRenderer.js``` to correctly render the bottom-to-top orientation of the gitGraph.
Resolves #5239

## :straight_ruler: Design Decisions

For ```gitGraphRenderer.js```, I reversed the array that stored the commit nodes so they can be rendered from bottom to top. I fixed the arrow and lines so that they can be correctly generated. 

### :clipboard: Tasks

Make sure you

- [ x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [ x] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/contributing.md#update-documentation) is used for all new features.
- [x ] :bookmark: targeted `develop` branch

2024-02-03 03:05 UTC, JingyuMarcelLee commented
If e2e tests are needed, I will work on them. I will also work on the documentation.

2024-02-03 05:15 UTC, sidharthv96 requested changes
Looks great, works well! Nice work 🚀 
Only some minor comments.

We also need 
- The documentation in `mermaid/packages/mermaid/src/docs/syntax/gitgraph.md`
- Rendering tests in `cypress/integration/rendering/gitGraph.spec.js`

2024-02-03 05:15 UTC, sidharthv96 commented on packages/mermaid/src/diagrams/git/gitGraphRenderer.js
> +          pos = commitPos[closestParent].y + commitStep;
```suggestion
        if (dir === 'TB' || dir === 'BT') {
          pos = commitPos[closestParent].y + commitStep;
```

2024-02-03 05:15 UTC, sidharthv96 commented on packages/mermaid/src/diagrams/git/gitGraphRenderer.js
> +      line.attr('y2', 30);
Let's avoid using [Magic numbers](https://stackoverflow.com/questions/47882/what-are-magic-numbers-and-why-do-some-consider-them-bad) in new commits.

2024-02-07 04:40 UTC, JingyuMarcelLee commented
Updated Documentation. Currently working on the Cypress E2E. I found that the ```GitGraph: { parallelCommits: true }``` option in the config breaks the BT orientation. I found a way around it and will work on it

2024-02-12 21:32 UTC, JingyuMarcelLee commented
Finished adding Cypress E2E test cases and logic for handling ```GitGraph: { parallelCommits: true }``` option in the config.

2024-02-13 06:34 UTC, sidharthv96 requested changes

2024-02-13 06:34 UTC, sidharthv96 commented on cypress/integration/rendering/gitGraph.spec.js
Love the tests!
Can you please revert the changes to the titles of existing tests, and wrap all the new tests in a `describe` block instead of editing the title?

Otherwise, our image comparison tests will not be happy with the changed titles.

2024-02-13 06:34 UTC, sidharthv96 commented on packages/mermaid/src/docs/syntax/gitgraph.md
> +## Orientation (v<MERMAID_RELEASE_VERSION>+)
This should be (v10.3.0+) itself, please add the `v\<MERMAID_RELEASE_VERSION>+` tag to the BT header.

2024-02-15 21:22 UTC, JingyuMarcelLee commented
I did make the requested changes, but please let me know if there are any other mistakes/errors. Sorry about the bad test/doc conventions. I should've read ```Contributing.md``` more carefully.

2024-03-19 14:42 UTC, sidharthv96 approved these changes

2024-03-19 14:42 UTC, sidharthv96 commented
Please resolve the conflicts.

2024-03-20 02:25 UTC, JingyuMarcelLee commented
Some of the refactoring effort in recent merges changed how the logic is being handled at the renderer side and it broke my tests and logic. 
![image](https://github.com/mermaid-js/mermaid/assets/46755208/e8c8c68f-f050-4211-87a1-e426ee444ee9)
I will fix them.

2024-03-20 05:21 UTC, JingyuMarcelLee commented
@sidharthv96 I am really sorry about this; I badly polluted the commits with some of the merge conflicts and had to hard reset to the up-to-date dev branch and recommit my feature

2024-03-23 12:41 UTC, merged