Add shellcheck support and robustify present shell scripts
mermaid-js/mermaid pull request #5294
Opened 2024-02-16 17:11 UTC by yarikoptic

_##_ :bookmark_tabs: Summary

https://www.shellcheck.net/ is great to robustify shell scripts, in particular make them work correctly when paths with spaces in them are involved somehow.

TODOs
- [ ] decide what to do about `args=${@:2}` since that semantic is unclear. ATM I just ignored that line while fixing the rest. See beed5fdc03ddfd9a6decbdd092d234946f78f2fd for the description of the gotcha there. One solution is to not do anything and keep that TODO. Another -- do fix it: I think it was intended to be used as an array, hence should become `args=( "${@:2}" )` but then uses should be adjusted accordingly. Please confirm that it was intended use.

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [ ] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/contributing.md#update-documentation) is used for all new features.
- [x] :bookmark: targeted `develop` branch

2024-02-16 17:13 UTC, yarikoptic commented on run
> +$(bold ./"$name" pnpm build)             # Prepare it for production
although looks odd, it is the only way to make it robust if script would ever be renamed to include space in the name. Alternatively that check could be skipped indeed.

2024-02-28 14:10 UTC, aloisklink requested changes
Thanks for your contribution :)

Your PR looks mostly great to me; however, I think adding quotes that `"$args"` (e.g. with quotes) instead of `$args` in the `run` script might break some behaviour. Can we change this to an array, like you recommend?

2024-02-28 14:10 UTC, aloisklink commented on .github/workflows/shellcheck.yml
> +          git grep -l '^#\( *shellcheck \|!\(/bin/\|/usr/bin/env \)\(sh\|bash\|dash\|ksh\)\)' | xargs shellcheck
Love this!

Just to tidy up, do you think it makes sense to move this into the [`.github/workflows/lint.yml`](https://github.com/mermaid-js/mermaid/blob/051ef598f669a40b783e3566631d7b31f8f1ab9f/.github/workflows/lint.yml) with the other lint job?

You'll have to move the `permissions: contents: read` into the `jobs.shellcheck` too.

2026-06-01 12:21 UTC, closed without merging

2026-06-01 12:45 UTC, yarikoptic commented
fair enough -- sorry it feel off my radar. let's see if claude could come of an assistance to me here now ;-)