feat(1624): first draft, prototype of context map grammar and diagram
mermaid-js/mermaid pull request #5353
Opened 2024-03-02 19:22 UTC by AngeloChecked

## :bookmark_tabs: Summary

Hi Mermaid Guys, this PR addresses the diagram discussed in this GitHub issue: [1624](https://github.com/mermaid-js/mermaid/issues/1624).

You can find a demo here: https://angelochecked.github.io/mermaid/

I've started implementing something, but it's in its early and raw stages. If anyone has a better prototype, please reach out to me (writing here) so I can contribute to it.

I've opened this draft pull request primarily to gather feedback from those more skilled than me in drawing 2D elements. I'll be working on this in my spare time, and I'm unsure when it will reach production grade. However, I'm very open to suggestions. If anyone wants to collaborate on the implementation of this diagram, please let me know.

I'm experimenting with rendering using plain d3 in this orphan branch: [contextMapDiagramGluedPrototype branch](https://github.com/AngeloChecked/mermaid/tree/contextMapDiagramGluedPrototype).

`Mermaid Devs`: I hope this draft PR doesn't create noise. If it does, I can close it and use the related issues to seek feedback. 
Additionally, feel free to share/post here any insights you believe could enhance both this contribution and the diagram implementation. Your input is greatly appreciated in beautifying and refining the the diagram implementation :).

Resolves #1624

## :straight_ruler: Design Decisions

I'm starting to experiment with the prototype design of this diagram using plain d3 in the simplest way possible. My decisions might be subjective, as I'm not particularly skilled in this domain of drawing d3 elements, but I'm learning along the way. I'm completely open to suggestions and improvements in the approach.

### :clipboard: Tasks

TODO:

- [x] :book: have read the [contribution guidelines](https://mermaid.js.org/community/contributing.html)
- [x] :bookmark: targeted `develop` branch
- [x] added diagram example

#### Big Picture

- [ ] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://mermaid.js.org/community/contributing.html#update-documentation) is used for all new features.
- [ ] styles and theme implementation

#### Parsing
- [x] Basic recognition of the `contextMap` scope
- [x] Simple parsing of nodes using the `contains` prefix keywords
- [x] Simple parsing of links
- [ ] Parsing of nodes with multiline `contains` keyword
- [ ]  additional features...? (teams...)

#### Diagram Rendering
- [x] Basic arrangement of nodes, labels, and links
- [x] Drawing simple nodes as ellipses
- [x] Drawing simple links
- [x] Drawing simple labels
- [ ] Resolving label collisions
- [ ] Resolving mid-link text collisions
- [ ] Preventing link intersection with nodes

2024-03-02 19:26 UTC, AngeloChecked commented
As mentioned in the todo, my current focus is on addressing some key pain points:

- Resolving label collisions
- Resolving mid-link text collisions
- Preventing link intersection with nodes

These issues are readily apparent in the [demo](https://angelochecked.github.io/mermaid/)

I'm completely open to suggestions and advice for enhancing the graph implementation. Please feel free to share any thoughts or ideas you have in mind!

2024-03-03 10:18 UTC, sidharthv96 commented
Can you please refer to these PRs and use langium instead of jison?  
We are migrating away from JISON, and would prefer new diagrams in langium, so that we don't have to do a migration. 

- https://github.com/mermaid-js/mermaid/pull/4839
- https://github.com/mermaid-js/mermaid/pull/4751

2024-03-03 10:55 UTC, AngeloChecked commented
> Can you please refer to these PRs and use langium instead of jison? We are migrating away from JISON, and would prefer new diagrams in langium, so that we don't have to do a migration.
> 
> * [feat: Add packet diagram #4839](https://github.com/mermaid-js/mermaid/pull/4839)
> * [feat: add `pie` langium parser #4751](https://github.com/mermaid-js/mermaid/pull/4751)

Hi! @sidharthv96, thanks a lot for the heads up! I totally missed that earlier. Could you point me towards the docs I should check out and i miss? Also, quick question: Should I stick with the 'packages/Mermaid' package or create a new one? Appreciate your help! :pray:

2024-03-05 18:40 UTC, Yokozuna59 commented
> But I'm worried I might have missed some docs. Did I overlook something?

Currently, the documentation is kind of outdated, so it may not be relevant in some aspects, especially when creating new diagrams with Langium.

> Also, quick question: Should I stick with the 'packages/Mermaid' package or create a new one? Appreciate your help! 🙏

You don't need to create a new package; just create new folders with the name of the diagram in:

- `packages/parser/src/language`
- `packages/mermaid/src/diagrams`

Then please refer to the [listed PRs above](https://github.com/mermaid-js/mermaid/pull/5353#issuecomment-1975112563) to know what other files should be modified or added.

> edit: is it acceptable for me to target the 'next' branch at this point?

Yes, the `packages/parser` exists only on the `next` branch for now. So it would be better if you checkouted from it instead of `develop`. It's fine if you targeted `next` now, but you may need to resolve conflict to update the current branch.

2024-06-20 15:11 UTC, nirname requested changes

2024-06-20 15:11 UTC, nirname commented on packages/mermaid/src/diagrams/context-map/parser/contextMap.jison
> +<comment>[^"*"]|[^"/"]             { /* skip */ }
If I understood this right
1. `[]` is a symbol class so you do not need to wrap values in quotes here, by adding `"` you add the symbol double quote to the symbol class as well. If you can escape them with `\` if needed. So your class excludes `"` (twice) and `*` from grammar, and second one excludes `"` (twice) and `/`, it should be
  ```
  ^[\*\/]
  ```
2. Does it mean that we prohibit * and / from comments? What if I would like to make such a comment /*******/ ?

2024-06-20 15:11 UTC, nirname commented on packages/mermaid/src/diagrams/context-map/parser/contextMap.jison
> +  | e EOF { return yy.getGraph() }
Why do you use getGraph() here? Everything you put in db (`yy` variable) during the parsing is already there

2024-06-20 15:11 UTC, nirname commented on packages/mermaid/src/diagrams/context-map/parser/contextMap.jison
> +  | e w
Could you be use more descriptive names for non-terminals? These are ok from grammars perspective, but quite unreadable

2024-06-22 08:52 UTC, AngeloChecked commented
Hi @nirname 

Thank you for the feedback! I'll update the naming convention.

Regarding Jison, I'm currently working on the ContextMap Langium parser [here](https://github.com/AngeloChecked/javascript-cml-parser), so the Jison version will be changed.

PS: yep, I initially called it 'mini-context-map' because it might not fully implement the [language reference](https://contextmapper.org/docs/language-reference/). However, I later removed the prefix as it didn't seem relevant.

2024-07-16 10:09 UTC, benr77 commented
We are really interested in this feature. Has there been any progress recently? Happy to help test or otherwise assist. Thanks.

2024-07-17 20:02 UTC, AngeloChecked commented
> We are really interested in this feature. Has there been any progress recently? Happy to help test or otherwise assist. Thanks.

Hi @benr77, sure!

I'm currently finishing the integration of the previous work with the new Langium parser. In a few days, I'll update this pull request with the master branch and resume work on the drawing part, which still lacks many features.

If you'd like, we can have a discussion on the Mermaid Discord once I wrap up my current task. Since I'm working on this in my spare time, my schedule isn't precise. I'm not an expert in this domain, so any insights or experience you can share would be super valuable. I'm also the first interested in making this kind of chart available on Mermaid, but consider that I'm treating it as an ongoing side project.

2024-07-18 04:31 UTC, benr77 commented
Hey @AngeloChecked thanks for the update. I am happy hear that this is still moving forward, and I completely understand it's a voluntary side project (I have several myself!).

Ping me a message when things are at a good stage to test, and I'll spend some time working with it and happy to report back with issues. I am no expert at context mapping or Mermaid but I am involved in a project whereby we are going to need this kind of diagramming a lot over the coming months so I'll have plenty of opportunities to test it.

Thanks!

2024-07-20 14:37 UTC, AngeloChecked commented
Hi @nirname, @sidharthv96, @Yokozuna59

I've force-pushed the entire branch with the new Langium parser implementation (and solved some linting).

I'm very open to any feedback, corrections, or improvements (config, naming, testing...). 

 Now, I'm shifting my focus back to the drawing part.

2024-11-23 19:36 UTC, hemalvarambhia commented
How can I start to use this feature on the live mermaid site?

2024-11-24 19:10 UTC, AngeloChecked commented
> How can I start to use this feature on the live mermaid site?

Hi @hemalvarambhia, I’m focusing on other stuff right now, so progress on this is slowing down. I plan to return on this in a few days. It’s far from ready... I’m dealing with issues like overlapping elements and experimenting with the spring embedder-like solutions. I don’t have a timeline yet for a usable version on the Mermaid website, but knowing there’s interest motivates me to prioritize it when I’m back. Thanks!

2024-11-24 19:12 UTC, hemalvarambhia commented
> Hi @hemalvarambhia, I’m focusing on other stuff right now, so progress on this is slowing down. I plan to return on this in a few days. It’s far from ready... I’m dealing with issues like overlapping elements and experimenting with the spring embedder-like solutions. I don’t have a timeline yet for a usable version on the Mermaid website, but knowing there’s interest motivates me to prioritize it when I’m back. Thanks!
@AngeloChecked that's perfect. I'll try to keep an eye. I love drawing context maps as they've been helpful.

2024-11-24 19:44 UTC, AngeloChecked commented
@hemalvarambhia Let me refocus on this project, and if you'd like, we can set up an online meeting.

2024-11-24 19:49 UTC, hemalvarambhia commented
> @hemalvarambhia Let me refocus on this project, and if you'd like, we can set up an online meeting.

@AngeloChecked I'd love it if you could refocus. I am drawing a context map at the moment. Being able to draw one would provide developers with important information for their work.

2024-12-02 13:22 UTC, hemalvarambhia commented
> if you'd like, we can set up an online meeting.

@AngeloChecked I am happy to have that conversation ❤️. Can Zoom work?

2025-02-13 15:15 UTC, hemalvarambhia commented
@AngeloChecked can a zoom session in March work?

2025-02-17 07:10 UTC, hemalvarambhia approved these changes
I am thankful to you for making progress. I definitely need this feature as, at work, I made a context boundary crisper and I have a translation layer package finally coming to life. If you are focusing on this, your timing's perfect.

2025-03-29 22:29 UTC, AngeloChecked commented
Hi everyone,
Here's a quick update: I’m back at it, mainly diving into the Spring Embedder. It’s a bit of a learning curve for me. Since working directly in Mermaid is challenging, I’m experimenting in a separate project for now. 

Once I have something solid, I’ll integrate and update the code.
My goal is to reach a kind of beta state, but I’m still can't see if this path is the most optimal.

I’m documenting everything I’m facing on in this document: 
[https://angelochecked.github.io/ContextMapSpringEmbedderNotes](https://angelochecked.github.io/ContextMapSpringEmbedderNotes/) 
I’ll be updating it as I progress. Feel free to leave any comments or thoughts in this discussion if you'd like!

2025-07-25 15:09 UTC, hemalvarambhia commented
@AngeloChecked Now that I have my translation layer running in prod, a Context Map would be great to help developers understand their terrain. In fact at the London Ruby User Group I shared my refactoring journey and it did energise people. I would love to mention that I used Mermaid to draw my Context Map the next time I present that talk.

2026-04-21 11:06 UTC, closed without merging