Updated the code to include nested namespaces for class diagrams
mermaid-js/mermaid pull request #5849
Opened 2024-09-09 15:22 UTC by ReneLombard

## :bookmark_tabs: Summary

Brief description about the content of your PR.

Resolves #<your issue id here>

## :straight_ruler: Design Decisions

Describe the way your implementation works or what design decisions you made if applicable.

### :clipboard: Tasks

Make sure you

- [ ] :book: have read the [contribution guidelines](https://mermaid.js.org/community/contributing.html)
- [ ] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://mermaid.js.org/community/contributing.html#update-documentation) is used for all new features.
- [ ] :butterfly: If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

2024-09-16 21:36 UTC, jgreywolf approved these changes

2024-09-17 21:47 UTC, skillmaker-dev commented
Does this support nested namespaces like i mentioned here in the examples? [Nested namespaces](https://github.com/mermaid-js/mermaid/issues/5487)

2024-09-19 07:34 UTC, ReneLombard commented
> Does this support nested namespaces like i mentioned here in the examples? [Nested namespaces](https://github.com/mermaid-js/mermaid/issues/5487)

This is an attempt to include nested namespaces, however, there is just a slight change in the proposed solution. Here are my thoughts.

In many commercial systems, it's common to encounter deeply nested namespaces, often 4 or 5 levels deep. For example:

Forexample, take the following namespace:
```
CompanyA.ProductA.Endpoint.VersionNumber.Models
```
with POCO classes 
```
PersonDto, CompanyDto
```

When visualized, this structure can become bloated, as shown in the image below:
![image](https://github.com/user-attachments/assets/8ef8c066-f04c-44f4-8ea0-855a6b89866b)

By using a single box around the section, you still effectively indicate that the namespace is nested, but it ensures the boxes don't dominate or overcrowd the diagram.

What are your thoughts @skillmaker-dev

2024-09-22 17:12 UTC, skillmaker-dev commented
> > Does this support nested namespaces like i mentioned here in the examples? [Nested namespaces](https://github.com/mermaid-js/mermaid/issues/5487)
> 
> This is an attempt to include nested namespaces, however, there is just a slight change in the proposed solution. Here are my thoughts.
> 
> In many commercial systems, it's common to encounter deeply nested namespaces, often 4 or 5 levels deep. For example:
> 
> Forexample, take the following namespace:
> 
> ```
> CompanyA.ProductA.Endpoint.VersionNumber.Models
> ```
> 
> with POCO classes
> 
> ```
> PersonDto, CompanyDto
> ```
> 
> When visualized, this structure can become bloated, as shown in the image below: ![image](https://private-user-images.githubusercontent.com/7263160/368884926-8ef8c066-f04c-44f4-8ea0-855a6b89866b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMjQyOTksIm5iZiI6MTcyNzAyMzk5OSwicGF0aCI6Ii83MjYzMTYwLzM2ODg4NDkyNi04ZWY4YzA2Ni1mMDRjLTQ0ZjQtOGVhMC04NTVhNmI4OTg2NmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjJUMTY1MzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjExYThlNDQ0NGZiNGI4ZGFhNDM4NGE1YTdhZGMzOTlmNTA4Y2I3Mjk2ZmZhNmYyODFhMjQyMTk3YjRjYjUwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.82bFdDKJvClCusxsmqdJEeJE2DbCg2IWzGV5zuowuMk)
> 
> By using a single box around the section, you still effectively indicate that the namespace is nested, but it ensures the boxes don't dominate or overcrowd the diagram.
> 
> What are your thoughts @skillmaker-dev

First of all Thanks for the great work you have done,

I agree that the structure might become bloated, but only when there are few classes or types, which make it more visibly bloated, but in a larger codebase it's negligible

It might be better to make it visible by supporting nested namespaces like this (currently not supported) : 

namespace A{
	namespace B{}
}

And what do you think about this? 
namespace A.B{
	namespace C{}
}

In this case, there would be only 2 boxes, one for the Namespace A.B and one for the nested namespace C, users can reduce the number of boxes by combining namespaces in one box ex: A.B.C which draws one box, and then the nested one ex: D which draws the nested box.

namespace A.B.C{
	namespace D{}
}

Also is it possible to have an empty namespace?

![image](https://github.com/user-attachments/assets/2d646299-4cf8-4067-850f-3fab0dc75444)

2024-09-23 09:43 UTC, ReneLombard commented
@skillmaker-dev 
I appreciate the idea of having the option of a nested blocks, but instead of having a namespace within another namespace, I prefer the concept of a package containing a namespace.

For example, rather than writing:

namespace CompanyA.ProductB.Endpoint.V1 {
    namespace Models
}

I would prefer something like:

package CompanyA.ProductB.Endpoint.V1 {
    namespace Models
}

This approach allows for reusing a package within different class diagrams, making it possible to reference a package as a whole, rather than redrawing all the individual components each time.

2024-09-23 19:01 UTC, skillmaker-dev commented
@ReneLombard wouldn't it be better to keep a consistent naming? Since package and namespace are interchangeable

2024-09-24 08:58 UTC, ReneLombard commented
@skillmaker-dev

In complex software systems, where multiple class diagrams exist for a single system, it's often not practical to represent the entire architecture in one comprehensive diagram. Attempting to do so results in an overly large and convoluted diagram that offers little additional value. Instead, the focus should be on the subsystem you are currently designing. This is where the logical separation between packages and namespaces becomes particularly advantageous.

If we consider other modeling tools like Enterprise Architect, the concept of a package is far from new and has long been established. Similarly, in software languages like .NET, the idea of packages is quite evident through the NuGet package manager. A NuGet package can encompass one or more packages, which in turn may bundle multiple namespaces. These namespaces contain classes that are eventually compiled into a single DLL, demonstrating the logical bundling of related functionalities.

Upon further reflection, it becomes increasingly clear that both packages and namespaces play equally important roles. You should have the flexibility to encapsulate a namespace within another namespace, just as a package can contain multiple namespaces. 

For reference, IBM's definition of UML Class Diagrams explicitly incorporates the concepts of both packages and namespaces:
[IBM’s UML Class Diagram Overview](https://developer.ibm.com/articles/the-class-diagram/)

I think it is valuable to create a separate issue on this matter to further investigate this, either way, i think it is still beneficial to be able to create dots in namespaces.

2024-09-24 15:33 UTC, skillmaker-dev commented
You are correct, This should be in a separate issue where more feedback is required from the community, and yes what you have done is valuable, it's good to have the possibility to include dots in namespace names.

2024-10-01 09:23 UTC, ReneLombard commented
@jgreywolf @sidharthv96 @knsv 

If there's any chance it could be reviewed and merged soon, I would greatly appreciate it. 
Please let me know if there's anything I can do to help expedite the process.

2024-10-01 14:41 UTC, sidharthv96 requested changes
LGTM! 
Can you please add a visual test in `cypress/integration/rendering/classDiagram-v2.spec.js`

2024-10-01 14:41 UTC, sidharthv96 commented on cypress/downloads/downloads.htm
Please remove this file

2024-10-02 14:34 UTC, ReneLombard commented on cypress/downloads/downloads.htm
Reworked

2024-10-03 03:56 UTC, merged