Packet diagram bit counts implements #5978
mermaid-js/mermaid pull request #5980
Opened 2024-10-18 19:12 UTC by BryanCrotazGivEnergy

## :bookmark_tabs: Summary

Implements #5978

Resolves #<your issue id here>

## :straight_ruler: Design Decisions

Added bit count to parser language and calculate start and end of each field on the fly

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://mermaid.js.org/community/contributing.html)
- [x] :computer: have added necessary unit/e2e tests.
- [x] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://mermaid.js.org/community/contributing.html#update-documentation) is used for all new features.
- [x] :butterfly: If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

2024-10-18 19:13 UTC, BryanCrotazGivEnergy commented
Tried to add a feature changeset but I get `Error: Failed to find where HEAD diverged from master. Does master exist?`

2024-10-18 19:48 UTC, BryanCrotazGivEnergy commented
@aloisklink I don't know why this is failing. It's showing no code coverage, but I've added tests that cover those lines, and traced them through with the debugger. Any ideas?

It was failing with prettier errors so I've run prettier on the repo.

2024-10-18 20:38 UTC, BryanCrotazGivEnergy commented
@aloisklink please review this PR - I think it's ready

2024-11-08 16:43 UTC, BryanCrotazGivEnergy commented
What's the process to get this approved?

2024-11-23 21:21 UTC, zanedp commented
I was considering using the "packet" type as a way to draw a memory map, which would be byte-scale instead of bit-scale. I wonder if a different syntax that didn't "tie" the diagram to a particular unit of measure would be more flexible? Shorting to `b` would make it so both "bits" and "bytes" make sense. But maybe doing something like `+5` to mean it's relative to the previous thing would work and be intuitive?

```
+16: Header
+32: Data
+4: Footer
```

2024-11-27 15:54 UTC, sidharthv96 requested changes
Excellent work @BryanCrotazGivEnergy, love the implementation and tests!
@zanedp makes a really good point, and I feel the + syntax looks better, and is easier to write & read. It'll also make the parser a bit simpler. 

Do you mind modifying the syntax to the + based one? Thank you!


### Current
```
packet-beta
title UDP Packet
0-15: "Source Port"
16-31: "Destination Port"
32-47: "Length"
48-63: "Checksum"
64-95: "Data (variable length)"
```


### bit(s) syntax
```
packet-beta
title UDP Packet
16bits: "Source Port"
16bits: "Destination Port"
16bits: "Length"
16bits: "Checksum"
32bits: "Data (variable length)"
```

### bit(s) syntax (mixed)
```
packet-beta
title UDP Packet
0-15: "Source Port"
16bits: "Destination Port"
32-47: "Length"
16bits: "Checksum"
32bits: "Data (variable length)"
```

### + syntax
```
packet-beta
title UDP Packet
+16: "Source Port"
+16: "Destination Port"
+16: "Length"
+16: "Checksum"
+32: "Data (variable length)"
```

### + syntax (mixed)
```
packet-beta
title UDP Packet
0-15: "Source Port"
+16: "Destination Port"
32-47: "Length"
+16: "Checksum"
+32: "Data (variable length)"
```

2024-11-27 15:58 UTC, BryanCrotazGivEnergy commented on docs/syntax/packet.md
> +````md
Sorry I don't understand - adding what?

2025-02-27 12:37 UTC, BryanCrotazGivEnergy commented
I've stopped working with packet diagrams, but I'd be very happy to hand over ownership if you want to fork off my fork.

2025-05-09 05:10 UTC, merged