Fix: Clusters break diagram when using elk layout
mermaid-js/mermaid pull request #6028
Opened 2024-11-06 18:23 UTC by yari-dewalt

## :bookmark_tabs: Summary

Fixes cluster nodes from breaking the diagram if rendered using elk.

Resolves #6027 

## :straight_ruler: Design Decisions

Removes true from being passed in to labelHelper() which was being treated as the shapeSvg resulting in `shapeSvg.insert() is not a function` error.

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://mermaid.js.org/community/contributing.html)
- [ ] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://mermaid.js.org/community/contributing.html#update-documentation) is used for all new features.
- [ ] :butterfly: If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

2024-11-06 18:27 UTC, yari-dewalt commented
Should also fix e2e tests that fail due to this issue.

2025-02-26 11:57 UTC, knsv commented
@yari-dewalt Please look at the lint changes

2025-02-26 18:03 UTC, yari-dewalt commented
@knsv Lint changes look good now

2026-06-02 12:02 UTC, pbrolin47 requested changes
Hi @yari-dewalt 
Sorry for the late response to this PR, but some minor things to address:
1) Since it's a bug-fix that can affect many users in a positive way, I think a change set with "patch" shall be added
2) Please add a rendering test showing the problem is resolved

2026-06-04 10:49 UTC, knsv commented
I think this issue has been resolved closing. Thanks nevertheless!

2026-06-04 10:49 UTC, closed without merging